# Generated by Django 2.1.2 on 2018-12-17 02:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0009_auto_20181215_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_Booking_Status_History',
            fields=[
                ('pk_status_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_from_api', models.CharField(blank=True, default='', max_length=32, verbose_name='Status From API')),
                ('status_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Status Date')),
                ('notes', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Notes')),
                ('status_date_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Status Date')),
                ('status_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Status code')),
                ('z_createdBy', models.CharField(blank=True, default='', max_length=40, verbose_name='Created By')),
                ('z_createdByAccount', models.CharField(blank=True, default='', max_length=40, verbose_name='Created By Account')),
                ('z_createdDate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Created Date')),
                ('z_createdTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created Timestamp')),
                ('z_modifiedBy', models.CharField(blank=True, default='', max_length=40, verbose_name='Modified By')),
                ('z_modifiedByAccount', models.CharField(blank=True, default='', max_length=40, verbose_name='Modified By Account')),
                ('status_preTranslation', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Status Pre-translation')),
                ('pod_signed_by', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Pod Signed By')),
                ('Responsible_Person', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Responsible Person')),
                ('updateViaAPI', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated via API')),
                ('fk_fpID', models.CharField(blank=True, default='', max_length=36, verbose_name='FP ID')),
                ('freightProvider', models.CharField(blank=True, default='', max_length=30, verbose_name='Freight Provider')),
                ('status_api', models.CharField(blank=True, default='', max_length=40, verbose_name='Status API')),
                ('depotName', models.CharField(blank=True, default='', max_length=30, verbose_name='Depot Name')),
                ('fk_booking_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='pages.Bookings')),
            ],
        ),
    ]
