# Generated by Django 2.1.2 on 2018-12-20 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_base64field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOK_0_BookingKeys',
            fields=[
                ('pk_auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_booking_id', models.CharField(blank=True, max_length=64, verbose_name='Client booking id')),
                ('filename', models.CharField(max_length=128, verbose_name='File name')),
                ('success', models.CharField(max_length=1, verbose_name='Success')),
                ('timestampCreated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='PickUp Available From')),
                ('client', models.CharField(blank=True, max_length=64, verbose_name='Client')),
                ('v_client_pk_consigment_num', models.CharField(blank=True, max_length=64, verbose_name='Consigment num')),
                ('l_000_client_acct_number', models.IntegerField(blank=True, verbose_name='Client account number')),
                ('l_011_client_warehouse_id', models.IntegerField(blank=True, verbose_name='Client warehouse Id')),
                ('l_012_client_warehouse_name', models.CharField(blank=True, max_length=240, verbose_name='Client warehouse Name')),
            ],
        ),
        migrations.CreateModel(
            name='BOK_1_headers',
            fields=[
                ('pk_auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_booking_id', models.CharField(blank=True, max_length=64, verbose_name='Client booking id')),
                ('b_21_b_pu_avail_from_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Available From')),
                ('b_003_b_service_name', models.CharField(blank=True, max_length=31, verbose_name='Service Name')),
                ('b_500_b_client_cust_job_code', models.CharField(blank=True, max_length=20, verbose_name='Client Job Code')),
                ('b_054_b_del_company', models.CharField(blank=True, max_length=100, verbose_name='Del company')),
                ('b_000_b_total_lines', models.IntegerField(blank=True, verbose_name='Total lines')),
                ('b_053_b_del_address_street', models.CharField(blank=True, max_length=100, verbose_name='Address street')),
                ('b_058_b_del_address_suburb', models.CharField(blank=True, max_length=40, verbose_name='Address suburb')),
                ('b_057_b_del_address_state', models.CharField(blank=True, max_length=20, verbose_name='Address state')),
                ('b_059_b_del_address_postalcode', models.IntegerField(blank=True, verbose_name='Address Postal Code')),
                ('v_client_pk_consigment_num', models.CharField(blank=True, max_length=64, verbose_name='Consigment num')),
                ('total_kg', models.FloatField(blank=True, verbose_name='Total Kg')),
                ('success', models.CharField(default=0, max_length=1, verbose_name='Success')),
            ],
        ),
        migrations.CreateModel(
            name='BOK_2_lines',
            fields=[
                ('pk_auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_booking_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Client booking id')),
                ('l_501_client_UOM', models.CharField(blank=True, max_length=31, null=True, verbose_name='Client UOM')),
                ('l_009_weight_per_each', models.FloatField(blank=True, null=True, verbose_name='Weight per each')),
                ('l_010_totaldim', models.FloatField(blank=True, null=True, verbose_name='Totaldim')),
                ('l_500_client_run_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='Client run code')),
                ('l_003_item', models.CharField(blank=True, max_length=128, null=True, verbose_name='Item')),
                ('v_client_pk_consigment_num', models.CharField(blank=True, max_length=64, null=True, verbose_name='Consigment num')),
                ('l_cubic_weight', models.FloatField(blank=True, null=True, verbose_name='Cubic Weight')),
                ('l_002_qty', models.IntegerField(blank=True, null=True, verbose_name='Address Postal Code')),
                ('success', models.CharField(blank=True, default=0, max_length=1, null=True, verbose_name='Success')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_Status_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_from_api', models.CharField(blank=True, default='', max_length=32, verbose_name='Status From API')),
                ('status_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Status Date')),
                ('notes', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Notes')),
                ('status_date_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Status Date')),
                ('status_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Status code')),
                ('z_createdBy', models.CharField(blank=True, default='', max_length=40, verbose_name='Created By')),
                ('z_createdByAccount', models.CharField(blank=True, default='', max_length=40, verbose_name='Created By Account')),
                ('z_createdTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created Timestamp')),
                ('z_modifiedBy', models.CharField(blank=True, default='', max_length=40, verbose_name='Modified By')),
                ('z_modifiedByAccount', models.CharField(blank=True, default='', max_length=40, verbose_name='Modified By Account')),
                ('z_modifiedTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Modified Timestamp')),
                ('status_preTranslation', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Status Pre-translation')),
                ('pod_signed_by', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Pod Signed By')),
                ('Responsible_Person', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Responsible Person')),
                ('updateViaAPI', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated via API')),
                ('fk_fpID', models.CharField(blank=True, default='', max_length=36, verbose_name='FP ID')),
                ('freightProvider', models.CharField(blank=True, default='', max_length=30, verbose_name='Freight Provider')),
                ('status_api', models.CharField(blank=True, default='', max_length=40, verbose_name='Status API')),
                ('depotName', models.CharField(blank=True, default='', max_length=30, verbose_name='Depot Name')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('b_bookingID_Visual', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='BookingID Visual')),
                ('b_dateBookedDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Booked Date')),
                ('puPickUpAvailFrom_Date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='PickUp Available From')),
                ('b_clientReference_RA_Numbers', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Client Reference Ra Numbers')),
                ('b_status', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Status')),
                ('vx_freight_provider', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Freight Provider')),
                ('vx_serviceName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Service Name')),
                ('s_05_LatestPickUpDateTimeFinal', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Lastest PickUp DateTime')),
                ('s_06_LatestDeliveryDateTimeFinal', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Latest Delivery DateTime')),
                ('v_FPBookingNumber', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='FP Booking Number')),
                ('puCompany', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Company')),
                ('deToCompanyName', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Company Name')),
                ('consignment_label_link', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Consignment')),
                ('error_details', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Error Detail')),
                ('is_printed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is printed')),
                ('shipping_label_base64', django_base64field.fields.Base64Field(blank=True, default='', max_length=255, null=True, verbose_name='Based64 Label')),
                ('kf_client_id', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='KF Client ID')),
                ('b_client_name', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Client Name')),
                ('pk_booking_id', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Booking ID')),
                ('zb_002_client_booking_key', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Client Booking Key')),
                ('fk_fp_pickup_id', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='KF FP pickup id')),
                ('pu_pickup_instructions_address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Pickup instrunctions address')),
            ],
        ),
        migrations.CreateModel(
            name='Client_employees',
            fields=[
                ('pk_id_client_emp', models.AutoField(primary_key=True, serialize=False)),
                ('name_last', models.CharField(max_length=30, verbose_name='last name')),
                ('name_first', models.CharField(max_length=30, verbose_name='first name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.IntegerField(verbose_name='phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Client_warehouse',
            fields=[
                ('pk_id_client_warehouse', models.AutoField(primary_key=True, serialize=False)),
                ('warehousename', models.CharField(max_length=230, verbose_name='warehoursename')),
                ('warehouse_address1', models.TextField(verbose_name='warehouse address1')),
                ('warehouse_address2', models.TextField(verbose_name='warehouse address2')),
                ('warehouse_state', models.TextField(verbose_name='warehouse state')),
                ('warehouse_suburb', models.TextField(verbose_name='warehouse suburb')),
                ('warehouse_phone_main', models.IntegerField(verbose_name='warehouse phone number')),
                ('warehouse_hours', models.IntegerField(verbose_name='warehouse hours')),
            ],
        ),
        migrations.CreateModel(
            name='DME_clients',
            fields=[
                ('pk_id_dme_client', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=230, verbose_name='warehoursename')),
                ('dme_account_num', models.IntegerField(verbose_name='dme account num')),
                ('phone', models.IntegerField(verbose_name='phone number')),
            ],
        ),
        migrations.CreateModel(
            name='DME_employees',
            fields=[
                ('pk_id_dme_emp', models.AutoField(primary_key=True, serialize=False)),
                ('name_last', models.CharField(max_length=30, verbose_name='last name')),
                ('name_first', models.CharField(max_length=30, verbose_name='first name')),
                ('Role', models.TextField(verbose_name='Role')),
                ('fk_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_payload', models.TextField(blank=True, default='', max_length=2000, verbose_name='Request Payload')),
                ('response', models.TextField(blank=True, default='', max_length=10000, verbose_name='Response')),
                ('request_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Request Timestamp')),
                ('request_status', models.CharField(blank=True, default='', max_length=20, verbose_name='Request Status')),
                ('request_type', models.CharField(blank=True, default='', max_length=30, verbose_name='Request Type')),
                ('fk_service_provider_id', models.CharField(blank=True, default='', max_length=36, verbose_name='Service Provider ID')),
                ('z_createdBy', models.CharField(blank=True, default='', max_length=40, verbose_name='Created By')),
                ('z_createdByAccount', models.CharField(blank=True, default='', max_length=40, verbose_name='Created By Account')),
                ('z_createdTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created Timestamp')),
                ('z_modifiedBy', models.CharField(blank=True, default='', max_length=40, verbose_name='Modified By')),
                ('z_modifiedByAccount', models.CharField(blank=True, default='', max_length=40, verbose_name='Modified By Account')),
                ('z_modifiedTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Modified Timestamp')),
                ('fk_booking_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.Bookings')),
            ],
        ),
        migrations.AddField(
            model_name='client_warehouse',
            name='fk_id_dme_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DME_clients'),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='fk_id_client_warehouse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Client_warehouse'),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='fk_id_dme_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DME_clients'),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='fk_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_clientPU_Warehouse',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.Client_warehouse'),
        ),
        migrations.AddField(
            model_name='booking_status_history',
            name='fk_booking_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.Bookings'),
        ),
    ]
