# Generated by Django 2.1.2 on 2018-12-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='deToAddressPostalCode',
            field=models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='DeliverTo Addr Postal Code'),
        ),
    ]
