# Generated by Django 2.1.2 on 2018-12-17 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20181215_0520'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Status_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_from_api', models.CharField(blank=True, default='', max_length=32, verbose_name='Status From API')),
                ('status_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Status Date')),
                ('notes', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Notes')),
                ('status_date_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Status Date')),
                ('status_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Status code')),
                ('z_createdBy', models.CharField(blank=True, default='', max_length=40, verbose_name='Created By')),
                ('z_createdByAccount', models.CharField(blank=True, default='', max_length=40, verbose_name='Created By Account')),
                ('z_createdTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created Timestamp')),
                ('z_modifiedBy', models.CharField(blank=True, default='', max_length=40, verbose_name='Modified By')),
                ('z_modifiedByAccount', models.CharField(blank=True, default='', max_length=40, verbose_name='Modified By Account')),
                ('z_modifiedTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Modified Timestamp')),
                ('status_preTranslation', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Status Pre-translation')),
                ('pod_signed_by', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Pod Signed By')),
                ('Responsible_Person', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Responsible Person')),
                ('updateViaAPI', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated via API')),
                ('fk_fpID', models.CharField(blank=True, default='', max_length=36, verbose_name='FP ID')),
                ('freightProvider', models.CharField(blank=True, default='', max_length=30, verbose_name='Freight Provider')),
                ('status_api', models.CharField(blank=True, default='', max_length=40, verbose_name='Status API')),
                ('depotName', models.CharField(blank=True, default='', max_length=30, verbose_name='Depot Name')),
                ('fk_booking_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='pages.Bookings')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_payload', models.CharField(blank=True, default='', max_length=64, verbose_name='Request Payload')),
                ('response', models.TextField(blank=True, default='', max_length=10000, verbose_name='Response')),
                ('request_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Request Timestamp')),
                ('request_status', models.CharField(blank=True, default='', max_length=20, verbose_name='Request Status')),
                ('request_type', models.CharField(blank=True, default='', max_length=30, verbose_name='Request Type')),
                ('fk_service_provider_id', models.CharField(blank=True, default='', max_length=36, verbose_name='Service Provider ID')),
                ('z_createdBy', models.CharField(blank=True, default='', max_length=40, verbose_name='Created By')),
                ('z_createdByAccount', models.CharField(blank=True, default='', max_length=40, verbose_name='Created By Account')),
                ('z_createdTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created Timestamp')),
                ('z_modifiedBy', models.CharField(blank=True, default='', max_length=40, verbose_name='Modified By')),
                ('z_modifiedByAccount', models.CharField(blank=True, default='', max_length=40, verbose_name='Modified By Account')),
                ('z_modifiedTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Modified Timestamp')),
                ('fk_booking_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='pages.Bookings')),
            ],
        ),
        migrations.RemoveField(
            model_name='api_booking_status_history',
            name='fk_booking_id',
        ),
        migrations.DeleteModel(
            name='API_Booking_Status_History',
        ),
    ]
