# Generated by Django 2.1.2 on 2018-12-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181217_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='request_payload',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Request Payload'),
        ),
    ]
