# Generated by Django 2.1.2 on 2018-12-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookings_detoaddresspostalcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_warehouse',
            new_name='Client_warehouses',
        ),
        migrations.RenameField(
            model_name='client_employees',
            old_name='fk_id_client_warehouse',
            new_name='fk_id_client_warehouses',
        ),
        migrations.RenameField(
            model_name='client_warehouses',
            old_name='pk_id_client_warehouse',
            new_name='pk_id_client_warehouses',
        ),
        migrations.AlterModelTable(
            name='bok_0_bookingkeys',
            table='bok_0_bookingkeys',
        ),
        migrations.AlterModelTable(
            name='bok_1_headers',
            table='bok_1_headers',
        ),
        migrations.AlterModelTable(
            name='bok_2_lines',
            table='bok_2_lines',
        ),
        migrations.AlterModelTable(
            name='booking_status_history',
            table='dme_booking_status_history',
        ),
        migrations.AlterModelTable(
            name='bookings',
            table='dme_bookings',
        ),
        migrations.AlterModelTable(
            name='client_employees',
            table='dme_client_employees',
        ),
        migrations.AlterModelTable(
            name='client_warehouses',
            table='dme_client_warehouses',
        ),
        migrations.AlterModelTable(
            name='dme_clients',
            table='dme_clients',
        ),
        migrations.AlterModelTable(
            name='dme_employees',
            table='dme_employees',
        ),
        migrations.AlterModelTable(
            name='log',
            table='dme_log',
        ),
    ]
