# Generated by Django 2.1.2 on 2018-12-23 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181221_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOK_3_lines_data',
            fields=[
                ('pk_auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_booking_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Client booking id')),
                ('fk_booking_id', models.CharField(blank=True, max_length=64, verbose_name='FK Booking Id')),
                ('v_client_pk_consigment_num', models.CharField(blank=True, max_length=64, null=True, verbose_name='Consigment num')),
                ('ld_001_qty', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('ld_002_model_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='Consigment num')),
                ('ld_003_item_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Item Description')),
                ('ld_004_fault_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='fault Description')),
                ('ld_005_item_serial_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='Item Serial Number')),
                ('ld_006_insurance_value', models.IntegerField(blank=True, null=True, verbose_name='Insurance Value')),
                ('ld_007_gap_ra', models.TextField(blank=True, max_length=300, null=True, verbose_name='Gap Ra')),
                ('ld_008_client_ref_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='Client Ref Number')),
                ('z_createdByAccount', models.CharField(blank=True, max_length=25, null=True, verbose_name='Created By Account')),
                ('z_createdTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=25, null=True, verbose_name='Modified By Account')),
                ('z_modifiedTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'bok_3_lines_data',
            },
        ),
    ]
