# Generated by Django 2.1.2 on 2018-12-23 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bok_3_lines_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_lines',
            fields=[
                ('pk_auto_id_lines', models.AutoField(primary_key=True, serialize=False)),
                ('fk_booking_id', models.CharField(blank=True, max_length=64, verbose_name='FK Booking Id')),
                ('e_type_of_packaging', models.CharField(blank=True, max_length=36, verbose_name='Type Of Packaging')),
                ('e_item_type', models.CharField(blank=True, max_length=64, verbose_name='Item Type')),
                ('e_pallet_type', models.CharField(blank=True, max_length=24, verbose_name='Pallet Type')),
                ('e_item', models.CharField(blank=True, max_length=56, verbose_name='Item')),
                ('e_qty', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('e_weightUOM', models.CharField(blank=True, max_length=56, verbose_name='Weight UOM')),
                ('e_weightPerEach', models.IntegerField(blank=True, null=True, verbose_name='Weight Per Each')),
                ('e_dimUOM', models.CharField(blank=True, max_length=10, verbose_name='Dim UOM')),
                ('e_dimLength', models.IntegerField(blank=True, null=True, verbose_name='Dim Length')),
                ('e_dimWidth', models.IntegerField(blank=True, null=True, verbose_name='Dim Width')),
                ('e_dimHeight', models.IntegerField(blank=True, null=True, verbose_name='Dim Height')),
                ('e_dangerousGoods', models.IntegerField(blank=True, null=True, verbose_name='Dangerous Goods')),
                ('e_insuranceValueEach', models.IntegerField(blank=True, null=True, verbose_name='Insurance Value Each')),
                ('discount_rate', models.IntegerField(blank=True, null=True, verbose_name='Discount Rate')),
                ('e_options1', models.CharField(blank=True, max_length=56, verbose_name='Option 1')),
                ('e_options2', models.CharField(blank=True, max_length=56, verbose_name='Option 2')),
                ('e_options3', models.CharField(blank=True, max_length=56, verbose_name='Option 3')),
                ('e_options4', models.CharField(blank=True, max_length=56, verbose_name='Option 4')),
                ('fk_service_id', models.CharField(blank=True, max_length=64, verbose_name='Service ID')),
                ('z_createdByAccount', models.CharField(blank=True, max_length=24, verbose_name='Created By Account')),
                ('z_documentUploadedUser', models.CharField(blank=True, max_length=24, verbose_name='Document Uploaded User')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=24, verbose_name='Modified By Account')),
                ('e_spec_clientRMA_Number', models.TextField(blank=True, max_length=300, verbose_name='Spec ClientRMA Number')),
                ('e_spec_customerReferenceNo', models.TextField(blank=True, max_length=200, verbose_name='Spec Customer Reference No')),
                ('taxable', models.BooleanField(blank=True, default=False, null=True, verbose_name='Taxable')),
                ('z_createdTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created Timestamp')),
                ('z_modifiedTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'dme_booking_lines',
            },
        ),
    ]
