# Generated by Django 2.1.2 on 2018-12-24 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_lines_data',
            fields=[
                ('pk_id_lines_data', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_booking_lines', models.CharField(blank=True, max_length=64, verbose_name='FK Booking Lines Id')),
                ('fk_booking_id', models.CharField(blank=True, max_length=64, verbose_name='FK Booking Id')),
                ('modelNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model Number')),
                ('itemDescription', models.TextField(blank=True, max_length=200, null=True, verbose_name='Item Description')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('itemFaultDescription', models.TextField(blank=True, max_length=200, null=True, verbose_name='Item Description')),
                ('insuranceValueEach', models.IntegerField(blank=True, null=True, verbose_name='Insurance Value Each')),
                ('gap_ra', models.TextField(blank=True, max_length=300, null=True, verbose_name='Gap Ra')),
                ('clientRefNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Client Ref Number')),
                ('itemSerialNumbers', models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Serial Numbers')),
                ('z_createdByAccount', models.CharField(blank=True, max_length=25, null=True, verbose_name='Created By Account')),
                ('z_createdTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=25, null=True, verbose_name='Modified By Account')),
                ('z_modifiedTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'dme_booking_lines_data',
            },
        ),
    ]
