# Generated by Django 2.1.2 on 2018-12-25 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_lines_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='DME_Base_Cost',
            field=models.IntegerField(blank=True, default=0, verbose_name='DME Base Cost'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='DME_GST_Percentage',
            field=models.IntegerField(blank=True, default=0, verbose_name='DME GST Percentage'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='DME_Notes',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='DME Notes'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='DME_price_from_client',
            field=models.IntegerField(blank=True, default=0, verbose_name='DME Price From Client'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_ImportedFromFile',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Imported File Filed'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_bookingNoOperatorDeliver',
            field=models.IntegerField(blank=True, default=0, verbose_name='Booking No Operator DE'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_booking_Category',
            field=models.TextField(blank=True, default='', max_length=400, null=True, verbose_name='Booking Categroy'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_booking_Notes',
            field=models.TextField(blank=True, default='', max_length=400, null=True, verbose_name='Booking Notes'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_booking_Priority',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Booking Priority'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_booking_no_operator_pickup',
            field=models.IntegerField(blank=True, default=0, verbose_name='Booking No Operator PU'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_booking_status_manual',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Booking Status Manual'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_booking_status_manual_DME',
            field=models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Booking Status Manual DME'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_booking_statusmanual_DME_Note',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Booking Status Manual DME Note'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_booking_tail_lift_deliver',
            field=models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Booking Tail Lift DE'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_booking_tail_lift_pickup',
            field=models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Booking Tail Lift PU'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_client_MarkUp_PercentageOverRide',
            field=models.IntegerField(blank=True, default=0, verbose_name='client MarkUp Percentage Override'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_client_Reference_RA_Numbers_lastupdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Client Reference RA Number Last Update'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_date_booked_by_dme',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Booked By DME'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_dateinvoice',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Invoice'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_email1_general_sent_Number_of_times',
            field=models.IntegerField(blank=True, default=0, verbose_name='Email1 General sent Number Of Times'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_email2_return_sent_numberofTimes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Email2 Return Sent Number Of Times'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_email3_pickup_sent_numberOfTimes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Email3 PU Sent Number Of Times'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_email4_futile_sent_number_of_times',
            field=models.IntegerField(blank=True, default=0, verbose_name='Email4 Futile Sent Number Of Times'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_email_Template_Name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Email Template Name'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_error_Capture',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Error Capture'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_error_code',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Error Code'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_handling_Instructions',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Handling Instructions'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_order_created',
            field=models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='Order Created'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_send_POD_eMail',
            field=models.IntegerField(blank=True, default=0, verbose_name='Send POD Email'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_status_API',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Status API'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booked_for_comm_communicate_via',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Booked Communicate Via'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_Created_For',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Booking Created For'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_Created_For_Email',
            field=models.CharField(blank=True, default='', max_length=35, null=True, verbose_name='Booking Created For Email'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Contact',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='DE Contact'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Deliver_By_Date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='DE By Date'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Deliver_By_Hours',
            field=models.IntegerField(blank=True, default=0, verbose_name='DE By Hours'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Deliver_By_Minutes',
            field=models.IntegerField(blank=True, default=0, verbose_name='De By Minutes'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Deliver_From_Date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='DE From Date'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Deliver_From_Hours',
            field=models.IntegerField(blank=True, default=0, verbose_name='DE From Hours'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Deliver_From_Minutes',
            field=models.IntegerField(blank=True, default=0, verbose_name='DE From Minutes'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Email',
            field=models.CharField(blank=True, default='', max_length=35, null=True, verbose_name='DE Email'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Email_Group_Emails',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='DE Email Group Emails'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Email_Group_Name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='DE Email Group Name'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Nospecific_Time',
            field=models.IntegerField(blank=True, default=0, verbose_name='No Specific Time'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Operating_Hours',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='DE Operating hours'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_Options',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='DE Options'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_TimeSlot_TimeStart',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='DE TimeSlot TimeStart'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_TimeSlot_Time_End',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='TimeSlot Time End'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_To_AddressType',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='DE Address Type'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_To_Address_City',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='DE Address City'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_To_Address_Country',
            field=models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='DE Address Country'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_To_Address_State',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='DE Address State'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_To_Address_Street_1',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='DE Address Street 1'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_To_Address_Street_2',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='DE Address Street 2'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_To_Address_Suburb',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='DE Address Suburb'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_To_Comm_Delivery_Communicate_Via',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='DE Communicate Via'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_Contact_FName',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='DE Contact First Name'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_Contact_F_LName',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='DE Contact Name'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_Contact_Lname',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='DE Contact Last Name'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_Phone_Main',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='DE Phone Main'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_Phone_Mobile',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='DE Phone Mobile'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_PickUp_Instructions_Address',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='DE Instructions Address'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_Pick_Up_Instructions_Contact',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='DE Instructions Contact'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_TimeSlot_Date_End',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='DE to TimeSlot Date End'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_WareHouse_Bay',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='DE Warehouse Bay'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_WareHouse_Number',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='DE Warehouse Number'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_addressed_Saved',
            field=models.IntegerField(blank=True, default=0, verbose_name='DE Addressed Saved'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kf_Add_ID_DE',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Add ID Deliver'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kf_Add_ID_PU',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Add ID Pick Up'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kf_FP_ID',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='FP ID'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kf_Invoice_Num_Booking',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Invoice Num Booking'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kf_booking_Created_For_ID',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Booking Created For ID'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kf_booking_quote_import_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Booking Quote Import ID'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kf_clientCustomerID_DE',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Custom ID Deliver'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kf_clientCustomerID_PU',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Custom ID Pick Up'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kf_email_Template',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Email Template'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kf_order_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kf_staff_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Staff ID'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='notes_cancel_Booking',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Notes Cancel Booking'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Actual_Date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='PU Actual Date'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Actual_PickUp_Time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Actual PU Time'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Address_City',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='PU Address City'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Address_Country',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='PU Address Country'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Address_PostalCode',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='PU Address Postal Code'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Address_State',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='PU Address State'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Address_Street_1',
            field=models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='PU Address Street 1'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Address_Suburb',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='PU Address Suburb'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Address_Type',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='PU Address Type'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Address_street_2',
            field=models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='PU Address Street 2'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Comm_Booking_Communicate_Via',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='PU Booking Communicate Via'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Contact_FName',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='PU Contact First Name'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Contact_F_L_Name',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='PU Contact Name'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Contact_Lname',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='PU Contact Last Name'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Email',
            field=models.CharField(blank=True, default='', max_length=35, null=True, verbose_name='PU Email'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_No_specified_Time',
            field=models.IntegerField(blank=True, default=0, verbose_name='PU No Specific Time'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Operting_Hours',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='PU Operating hours'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Phone_Main',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='PU Phone Main'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_Phone_Mobile',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='PU Phone Mobile'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_Avail_From_Date_DME',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='PU Available From Date DME'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_Avail_Time_Hours',
            field=models.IntegerField(blank=True, default=0, verbose_name='PU Available Time Hours'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_Avail_Time_Hours_DME',
            field=models.IntegerField(blank=True, default=0, verbose_name='PU Available Time Hours DME'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_Avail_Time_Minutes',
            field=models.IntegerField(blank=True, default=0, verbose_name='PU Available Time Minutes'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_Avail_Time_Minutes_DME',
            field=models.IntegerField(blank=True, default=0, verbose_name='PU Available Time Minutes DME'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_By_Date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='PickUp By Date'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_By_Date_DME',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='PU By Date DME'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_By_Time_Hours',
            field=models.IntegerField(blank=True, default=0, verbose_name='PU By Time Hours'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_By_Time_Hours_DME',
            field=models.IntegerField(blank=True, default=0, verbose_name='PU By Time Hours DME'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_By_Time_Minutes',
            field=models.IntegerField(blank=True, default=0, verbose_name='PU By Time Minutes'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_By_Time_Minutes_DME',
            field=models.IntegerField(blank=True, default=0, verbose_name='PU By Time Minutes DME'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_Instructions_Contact',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='PU Instructions Contact'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_PickUp_TimeSlot_TimeEnd',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='PU TimeSlot TimeEnd'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_WareHouse_Bay',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='PU Warehouse Bay'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_WareHouse_Number',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='PU Warehouse Number'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_addressed_Saved',
            field=models.IntegerField(blank=True, default=0, verbose_name='PU Addressed Saved'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_email_Group',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='PU Email Group'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_email_Group_Name',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='PU Email Group Name'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='rec_do_not_Invoice',
            field=models.IntegerField(blank=True, default=0, verbose_name='Rec Doc Not Invoice'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='s_02_Booking_Cutoff_Time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Booking Cutoff Time'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='s_04_Max_Duration_To_Delivery_Number',
            field=models.IntegerField(blank=True, default=0, verbose_name='04 Max Duration To Delivery Number'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='s_05_Latest_PickUp_Date_Time_Override',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Latest PU DateTime Override'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='s_05_Latest_Pick_Up_Date_TimeSet',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Latest PU DateTime Set'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='s_06_Latest_Delivery_Date_TimeSet',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Latest DE DateTime Set'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='s_06_Latest_Delivery_Date_Time_Override',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Latest DE DateTime Override'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='s_07_PickUp_Progress',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='PU Progress'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='s_08_Delivery_Progress',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='DE Progress'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='s_20_Actual_Pickup_TimeStamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Actual PU TimeStamp'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='total_1_KG_weight_override',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total 1Kg Weight Override'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='total_Cubic_Meter_override',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total Cubic Meter Override'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='total_lines_qty_override',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total Lines Qty Override'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_customer_code',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Customer Code'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_price_Booking',
            field=models.IntegerField(blank=True, default=0, verbose_name='Price Booking'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_serviceCode_DME',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Service Code DME'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_serviceDelivery_Days',
            field=models.IntegerField(blank=True, default=0, verbose_name='Service DE Days'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_serviceTime_End',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Service Time End'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_serviceTime_Start',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Service Time Start'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_service_DeliveryHours_TO_PU',
            field=models.IntegerField(blank=True, default=0, verbose_name='Service DE Hours To PU'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_service_Delivery_Days_Percentage_Days_TO_PU',
            field=models.IntegerField(blank=True, default=0, verbose_name='Service DE days Percentage Days To PU'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_service_Delivery_Hours',
            field=models.IntegerField(blank=True, default=0, verbose_name='Service DE Hours'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_service_Type',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Service Type'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_service_Type_2',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Service Type 2'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_service_Type_ID',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Service Type ID'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='v_vehicle_Type',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Vehicle Type'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='vx_FP_ETA_Date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='FP ETA Date'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='vx_FP_ETA_Time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='FP ETA Time'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='vx_Transit_Duration',
            field=models.IntegerField(blank=True, default=0, verbose_name='Transit Duration'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='vx_freight_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Freight Time'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='vx_futile_Booking_Notes',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Futile Booking Notes'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='vx_price_Booking',
            field=models.IntegerField(blank=True, default=0, verbose_name='Price Booking'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='vx_price_Tax',
            field=models.IntegerField(blank=True, default=0, verbose_name='Price Tax'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='vx_price_Total_Sell_Price_Override',
            field=models.IntegerField(blank=True, default=0, verbose_name='Price Total Sell Price Override'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='vx_service_Name_ID',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Service Name ID'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='x_Data_Entered_Via',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Data Entered Via'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='x_ReadyStatus',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Ready Status'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='x_booking_Created_With',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Booking Created With'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_API_Issue',
            field=models.IntegerField(blank=True, default=0, verbose_name='Api Issue'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_CreatedByAccount',
            field=models.TextField(blank=True, default='', max_length=30, null=True, verbose_name='Created By Account'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_CreatedTimestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created By Account'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_ModifiedByAccount',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Modified By Account'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_ModifiedTimestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Modified By Account'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_Notes_Bugs',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Notes Bugs'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_admin_dme_invoice_number',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Admin DME Invoice Number'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_api_issue_update_flag_500',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='API Issue Update Flag 500'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_included_with_manifest_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Included With Manifest Date'),
        ),
    ]
