# Generated by Django 2.1.2 on 2018-12-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181225_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='fk_booking_id',
            new_name='fk_booking',
        ),
    ]
