# Generated by Django 2.1.2 on 2018-12-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181228_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='de_To_Address_PostalCode',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='DE Address Postal Code'),
        ),
    ]
