# Generated by Django 2.1.2 on 2018-12-29 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bookings_de_to_address_postalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='s_21_Actual_Delivery_TimeStamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Actual DE TimeStamp'),
        ),
    ]
