# Generated by Django 2.1.2 on 2018-12-29 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bookings_s_21_actual_delivery_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_000_1_b_clientReference_RA_Numbers',
            field=models.CharField(blank=True, max_length=500, verbose_name='b_000_1_b_clientReference_RA_Numbers'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_000_2_b_price',
            field=models.IntegerField(blank=True, default=0, max_length=4, verbose_name='b_000_2_b_price'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_001_b_freight_provider',
            field=models.CharField(blank=True, max_length=36, verbose_name='b_001_b_freight_provider'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_002_b_vehicle_type',
            field=models.CharField(blank=True, max_length=36, verbose_name='b_002_b_vehicle_type'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_005_b_created_for',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_005_b_created_for'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_006_b_created_for_email',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_006_b_created_for_email'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_007_b_ready_status',
            field=models.CharField(blank=True, max_length=24, verbose_name='b_007_b_ready_status'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_008_b_category',
            field=models.CharField(blank=True, max_length=24, verbose_name='b_008_b_category'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_009_b_priority',
            field=models.CharField(blank=True, max_length=20, verbose_name='b_009_b_priority'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_010_b_notes',
            field=models.CharField(blank=True, max_length=500, verbose_name='b_010_b_notes'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_012_b_driver_bring_connote',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='b_012_b_driver_bring_connote'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_013_b_package_job',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='b_013_b_package_job'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_014_b_pu_handling_instructions',
            field=models.CharField(blank=True, max_length=100, verbose_name='b_014_b_pu_handling_instructions'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_015_b_pu_instructions_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='b_015_b_pu_instructions_contact'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_016_b_pu_instructions_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='b_016_b_pu_instructions_address'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_017_b_pu_warehouse_num',
            field=models.CharField(blank=True, max_length=10, verbose_name='b_017_b_pu_warehouse_num'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_018_b_pu_warehouse_bay',
            field=models.CharField(blank=True, max_length=10, verbose_name='b_018_b_pu_warehouse_bay'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_019_b_pu_tail_lift',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='b_019_b_pu_tail_lift'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_020_b_pu_num_operators',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='b_020_b_pu_num_operators'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_022_b_pu_avail_from_time_hour',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='b_022_b_pu_avail_from_time_hour'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_023_b_pu_avail_from_time_minute',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='b_023_b_pu_avail_from_time_minute'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_024_b_pu_by_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='b_024_b_pu_by_date'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_025_b_pu_by_time_hour',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='b_025_b_pu_by_time_hour'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_026_b_pu_by_time_minute',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='b_026_b_pu_by_time_minute'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_027_b_pu_address_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='b_027_b_pu_address_type'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_028_b_pu_company',
            field=models.CharField(blank=True, max_length=40, verbose_name='b_028_b_pu_company'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_028_b_pu_compb_029_b_pu_address_street_1any',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_029_b_pu_address_street_1'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_030_b_pu_address_street_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_030_b_pu_address_street_2'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_031_b_pu_address_state',
            field=models.CharField(blank=True, max_length=20, verbose_name='b_031_b_pu_address_state'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_032_b_pu_address_suburb',
            field=models.CharField(blank=True, max_length=20, verbose_name='b_032_b_pu_address_suburb'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_033_b_pu_address_postalcode',
            field=models.CharField(blank=True, max_length=15, verbose_name='b_033_b_pu_address_postalcode'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_034_b_pu_address_country',
            field=models.CharField(blank=True, max_length=15, verbose_name='b_034_b_pu_address_country'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_035_b_pu_contact_full_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_035_b_pu_contact_full_name'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_036_b_pu_email_group',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_036_b_pu_email_group'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_037_b_pu_email',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_037_b_pu_email'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_038_b_pu_phone_main',
            field=models.CharField(blank=True, max_length=25, verbose_name='b_038_b_pu_phone_main'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_039_b_pu_phone_mobile',
            field=models.CharField(blank=True, max_length=25, verbose_name='b_039_b_pu_phone_mobile'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_040_b_pu_communicate_via',
            field=models.CharField(blank=True, max_length=30, verbose_name='b_040_b_pu_communicate_via'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_041_b_del_tail_lift',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='b_041_b_del_tail_lift'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_042_b_del_num_operators',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='b_042_b_del_num_operators'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_043_b_del_instructions_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='b_043_b_del_instructions_contact'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_044_b_del_instructions_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='b_044_b_del_instructions_address'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_045_b_del_warehouse_bay',
            field=models.CharField(blank=True, max_length=100, verbose_name='b_045_b_del_warehouse_bay'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_046_b_del_warehouse_number',
            field=models.CharField(blank=True, max_length=1, verbose_name='b_046_b_del_warehouse_number'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_047_b_del_avail_from_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='b_047_b_del_avail_from_date'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_048_b_del_avail_from_time_hour',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='b_048_b_del_avail_from_time_hour'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_049_b_del_avail_from_time_minute',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='b_049_b_del_avail_from_time_minute'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_050_b_del_by_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='b_050_b_del_by_date'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_051_b_del_by_time_hour',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='b_051_b_del_by_time_hour'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_052_b_del_by_time_minute',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='b_052_b_del_by_time_minute'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_055_b_del_address_street_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_055_b_del_address_street_1'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_056_b_del_address_street_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_056_b_del_address_street_2'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_060_b_del_address_country',
            field=models.CharField(blank=True, max_length=15, verbose_name='b_060_b_del_address_country'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_061_b_del_contact_full_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_061_b_del_contact_full_name'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_062_b_del_email_group',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_062_b_del_email_group'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_063_b_del_email',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_063_b_del_email'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_064_b_del_phone_main',
            field=models.CharField(blank=True, max_length=25, verbose_name='b_064_b_del_phone_main'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_065_b_del_phone_mobile',
            field=models.CharField(blank=True, max_length=25, verbose_name='b_065_b_del_phone_mobile'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_066_b_del_communicate_via',
            field=models.CharField(blank=True, max_length=30, verbose_name='b_066_b_del_communicate_via'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_500_b_client_UOM',
            field=models.CharField(blank=True, max_length=20, verbose_name='b_500_b_client_UOM'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_501_b_client_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='b_501_b_client_code'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_client_max_book_amount',
            field=models.IntegerField(blank=True, default=0, max_length=6, verbose_name='b_client_max_book_amount'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='date_processed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_processed'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='fk_client_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='fk_client_id'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='pk_header_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='pk_header_id'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='pu_addressed_saved',
            field=models.CharField(blank=True, max_length=3, verbose_name='pu_addressed_saved'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='vx_serviceType_XXX',
            field=models.CharField(blank=True, max_length=50, verbose_name='vx_serviceType_XXX'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='warehouse',
            field=models.CharField(blank=True, max_length=32, verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='z_createdTimeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='z_createdTimeStamp'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_000_b_total_lines',
            field=models.IntegerField(blank=True, max_length=4, verbose_name='b_000_b_total_lines'),
        ),
    ]
