# Generated by Django 2.1.2 on 2018-12-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181229_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='z_label_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='PDF Url'),
        ),
    ]
