# Generated by Django 2.1.2 on 2019-01-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_bookings_z_label_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bok_1_headers',
            old_name='b_21_b_pu_avail_from_date',
            new_name='b_021_b_pu_avail_from_date',
        ),
        migrations.RenameField(
            model_name='bok_1_headers',
            old_name='b_028_b_pu_compb_029_b_pu_address_street_1any',
            new_name='b_029_b_pu_address_street_1any',
        ),
    ]
