# Generated by Django 2.1.2 on 2019-01-03 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190103_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_000_1_b_clientReference_RA_Numbers',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='b_000_1_b_clientReference_RA_Numbers'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_000_2_b_price',
            field=models.IntegerField(blank=True, default=0, max_length=4, null=True, verbose_name='b_000_2_b_price'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_000_b_total_lines',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='b_000_b_total_lines'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_001_b_freight_provider',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='b_001_b_freight_provider'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_002_b_vehicle_type',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='b_002_b_vehicle_type'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_003_b_service_name',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_005_b_created_for',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_005_b_created_for'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_006_b_created_for_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_006_b_created_for_email'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_007_b_ready_status',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='b_007_b_ready_status'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_008_b_category',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='b_008_b_category'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_009_b_priority',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='b_009_b_priority'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_010_b_notes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='b_010_b_notes'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_014_b_pu_handling_instructions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='b_014_b_pu_handling_instructions'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_015_b_pu_instructions_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='b_015_b_pu_instructions_contact'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_016_b_pu_instructions_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='b_016_b_pu_instructions_address'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_017_b_pu_warehouse_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='b_017_b_pu_warehouse_num'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_018_b_pu_warehouse_bay',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='b_018_b_pu_warehouse_bay'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_020_b_pu_num_operators',
            field=models.IntegerField(blank=True, default=0, max_length=2, null=True, verbose_name='b_020_b_pu_num_operators'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_022_b_pu_avail_from_time_hour',
            field=models.IntegerField(blank=True, default=0, max_length=2, null=True, verbose_name='b_022_b_pu_avail_from_time_hour'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_023_b_pu_avail_from_time_minute',
            field=models.IntegerField(blank=True, default=0, max_length=2, null=True, verbose_name='b_023_b_pu_avail_from_time_minute'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_024_b_pu_by_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='b_024_b_pu_by_date'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_025_b_pu_by_time_hour',
            field=models.IntegerField(blank=True, default=0, max_length=2, null=True, verbose_name='b_025_b_pu_by_time_hour'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_026_b_pu_by_time_minute',
            field=models.IntegerField(blank=True, default=0, max_length=2, null=True, verbose_name='b_026_b_pu_by_time_minute'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_027_b_pu_address_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='b_027_b_pu_address_type'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_028_b_pu_company',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='b_028_b_pu_company'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_029_b_pu_address_street_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_029_b_pu_address_street_1'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_030_b_pu_address_street_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_030_b_pu_address_street_2'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_031_b_pu_address_state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='b_031_b_pu_address_state'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_032_b_pu_address_suburb',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='b_032_b_pu_address_suburb'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_033_b_pu_address_postalcode',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='b_033_b_pu_address_postalcode'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_034_b_pu_address_country',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='b_034_b_pu_address_country'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_035_b_pu_contact_full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_035_b_pu_contact_full_name'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_036_b_pu_email_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_036_b_pu_email_group'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_037_b_pu_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_037_b_pu_email'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_038_b_pu_phone_main',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='b_038_b_pu_phone_main'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_039_b_pu_phone_mobile',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='b_039_b_pu_phone_mobile'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_040_b_pu_communicate_via',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='b_040_b_pu_communicate_via'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_042_b_del_num_operators',
            field=models.IntegerField(blank=True, default=0, max_length=2, null=True, verbose_name='b_042_b_del_num_operators'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_043_b_del_instructions_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='b_043_b_del_instructions_contact'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_044_b_del_instructions_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='b_044_b_del_instructions_address'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_045_b_del_warehouse_bay',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='b_045_b_del_warehouse_bay'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_046_b_del_warehouse_number',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='b_046_b_del_warehouse_number'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_047_b_del_avail_from_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='b_047_b_del_avail_from_date'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_048_b_del_avail_from_time_hour',
            field=models.IntegerField(blank=True, default=0, max_length=2, null=True, verbose_name='b_048_b_del_avail_from_time_hour'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_049_b_del_avail_from_time_minute',
            field=models.IntegerField(blank=True, default=0, max_length=2, null=True, verbose_name='b_049_b_del_avail_from_time_minute'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_050_b_del_by_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='b_050_b_del_by_date'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_051_b_del_by_time_hour',
            field=models.IntegerField(blank=True, default=0, max_length=2, null=True, verbose_name='b_051_b_del_by_time_hour'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_052_b_del_by_time_minute',
            field=models.IntegerField(blank=True, default=0, max_length=2, null=True, verbose_name='b_052_b_del_by_time_minute'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_053_b_del_address_street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address street'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_054_b_del_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Del company'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_055_b_del_address_street_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_055_b_del_address_street_1'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_056_b_del_address_street_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_056_b_del_address_street_2'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_057_b_del_address_state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Address state'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_058_b_del_address_suburb',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Address suburb'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_059_b_del_address_postalcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Address Postal Code'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_060_b_del_address_country',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='b_060_b_del_address_country'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_061_b_del_contact_full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_061_b_del_contact_full_name'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_062_b_del_email_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_062_b_del_email_group'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_063_b_del_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_063_b_del_email'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_064_b_del_phone_main',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='b_064_b_del_phone_main'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_065_b_del_phone_mobile',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='b_065_b_del_phone_mobile'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_066_b_del_communicate_via',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='b_066_b_del_communicate_via'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_500_b_client_UOM',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='b_500_b_client_UOM'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_500_b_client_cust_job_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Client Job Code'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_501_b_client_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='b_501_b_client_code'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='b_client_max_book_amount',
            field=models.IntegerField(blank=True, default=0, max_length=6, null=True, verbose_name='b_client_max_book_amount'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='fk_client_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='fk_client_id'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='pk_header_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='pk_header_id'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='pu_addressed_saved',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='pu_addressed_saved'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='success',
            field=models.CharField(default=0, max_length=1, null=True, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='total_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Kg'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='v_client_pk_consigment_num',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Consigment num'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='vx_serviceType_XXX',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='vx_serviceType_XXX'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='warehouse',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='warehouse'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='z_createdTimeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='z_createdTimeStamp'),
        ),
    ]
