# Generated by Django 2.1.2 on 2019-01-04 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190103_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='b_date_booked_by_dme',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Booked By DME'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='b_dateinvoice',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Invoice'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='de_Deliver_By_Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='DE By Date'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='de_Deliver_From_Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='DE From Date'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='de_to_TimeSlot_Date_End',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='DE to TimeSlot Date End'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='puPickUpAvailFrom_Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='PickUp Available From'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_Actual_Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='PU Actual Date'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_PickUp_Avail_From_Date_DME',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='PU Available From Date DME'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_PickUp_By_Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='PickUp By Date'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_PickUp_By_Date_DME',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='PU By Date DME'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='vx_FP_ETA_Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='FP ETA Date'),
        ),
    ]
