# Generated by Django 2.1.2 on 2019-01-04 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190104_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='pu_PickUp_TimeSlot_TimeEnd',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 1, 4, 22, 0), null=True, verbose_name='PU TimeSlot TimeEnd'),
        ),
    ]
