# Generated by Django 2.1.2 on 2019-01-04 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190104_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='de_TimeSlot_TimeStart',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 1, 4, 22, 0), null=True, verbose_name='DE TimeSlot TimeStart'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='de_TimeSlot_Time_End',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 1, 4, 22, 0), null=True, verbose_name='TimeSlot Time End'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_Actual_PickUp_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 1, 4, 22, 0), null=True, verbose_name='Actual PU Time'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='s_02_Booking_Cutoff_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 1, 4, 22, 0), null=True, verbose_name='Booking Cutoff Time'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='v_serviceTime_End',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 1, 4, 22, 0), null=True, verbose_name='Service Time End'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='v_serviceTime_Start',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 1, 4, 22, 0), null=True, verbose_name='Service Time Start'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='vx_FP_ETA_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 1, 4, 22, 0), null=True, verbose_name='FP ETA Time'),
        ),
    ]
