# Generated by Django 2.1.2 on 2019-08-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0127_auto_20190829_0849")]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="z_calculated_ETA",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        )
    ]
