# Generated by Django 2.1.2 on 2019-11-26 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_auto_20191124_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utl_sql_queries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sql_title', models.CharField(blank=True, max_length=36, null=True, verbose_name='SQL Title')),
                ('sql_query', models.TextField(blank=True, null=True, verbose_name='SQL Query')),
                ('sql_description', models.TextField(blank=True, null=True, verbose_name='SQL Description')),
                ('sql_notes', models.TextField(blank=True, null=True, verbose_name='SQL Notes')),
                ('z_createdByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by account')),
                ('z_createdTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by account')),
                ('z_modifiedTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'utl_sql_queries',
            },
        )
    ]
