# Generated by Django 2.1.2 on 2019-12-09 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0156_auto_20191202_0102")]

    operations = [
        migrations.RemoveField(model_name="bok_3_lines_data", name="fk_booking_id"),
        migrations.AddField(
            model_name="bok_2_lines",
            name="pk_booking_lines_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="bok_3_lines_data",
            name="fk_booking_lines_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="bok_3_lines_data",
            name="fk_header_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
