# Generated by Django 2.1.2 on 2019-12-18 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0156_auto_20191202_0102")]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_008_b_category",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="b_008_b_category"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_booking_Category",
            field=models.CharField(
                blank=True,
                default="",
                max_length=63,
                null=True,
                verbose_name="Booking Categroy",
            ),
        ),
    ]
