# Generated by Django 2.1.2 on 2019-12-10 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0157_auto_20191209_0223")]

    operations = [
        migrations.RemoveField(
            model_name="booking_lines_data", name="fk_id_booking_lines"
        ),
        migrations.AddField(
            model_name="booking_lines",
            name="pk_booking_lines_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="booking_lines_data",
            name="fk_booking_lines_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="FK Booking Lines Id"
            ),
        ),
    ]
