# Generated by Django 2.1.2 on 2019-12-10 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0158_auto_20191210_0021")]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="x_ReadyStatus",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                null=True,
                verbose_name="Ready Status",
            ),
        )
    ]
