# Generated by Django 2.1.2 on 2019-12-10 00:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0159_auto_20191210_0025")]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_021_b_pu_avail_from_date",
            field=models.DateField(
                blank=True, default=datetime.datetime.now, verbose_name="Available From"
            ),
        )
    ]
