# Generated by Django 2.1.2 on 2019-12-10 00:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0160_auto_20191210_0035")]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_024_b_pu_by_date",
            field=models.DateField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        )
    ]
