# Generated by Django 2.1.2 on 2019-12-10 00:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0161_auto_20191210_0038")]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_047_b_del_avail_from_date",
            field=models.DateField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_050_b_del_by_date",
            field=models.DateField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
    ]
