# Generated by Django 2.1.2 on 2020-01-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0162_auto_20200112_0637"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fp_store_booking_log",
            old_name="fp_store_scheduled_date",
            new_name="delivery_booking",
        ),
    ]
