# Generated by Django 2.1.2 on 2020-01-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_auto_20200112_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='z_connote_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_downloaded_connote_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='api_booking_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='dme_reports',
            name='z_downloadedTimeStamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Downloaded Timestamp'),
        ),
        migrations.AlterField(
            model_name='utl_states',
            name='fk_country_id',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
