# Generated by Django 2.1.2 on 2020-03-13 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0180_auto_20200221_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='z_connote_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_downloaded_connote_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bok_3_lines_data',
            name='fk_booking_lines_id',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='booking_lines_data',
            name='fk_booking_lines_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True,
                                   verbose_name='FK Booking Lines Id'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='api_booking_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='dme_reports',
            name='z_downloadedTimeStamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Downloaded Timestamp'),
        ),
        migrations.AlterField(
            model_name='utl_states',
            name='fk_country_id',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
