# Generated by Django 2.1.2 on 2020-03-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0181_auto_20200313_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='api_booking_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='api.API_booking_quotes'),
        ),
    ]
