# Generated by Django 2.1.2 on 2020-03-13 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0184_auto_20200313_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_lines',
            name='pk_booking_lines_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bok_2_lines',
            name='pk_booking_lines_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='PK Booking Line'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='api_booking_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='b_booking_Category',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Booking Categroy'),
        ),
    ]
