# Generated by Django 2.1.2 on 2020-03-17 06:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0185_auto_20200313_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoho_tokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(default=None, max_length=255)),
                ('refresh_token', models.CharField(default=None, max_length=255)),
                ('createdTimeStamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'zoho_tokens',
            },
        ),
        migrations.AlterField(
            model_name='bookings',
            name='api_booking_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='api.API_booking_quotes'),
        ),
    ]
