# Generated by Django 2.1.2 on 2020-03-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0186_auto_20200317_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='api_booking_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='zoho_tokens',
            name='createdTimeStamp',
            field=models.DateTimeField(default=None),
        ),
    ]
