# Generated by Django 2.1.2 on 2020-03-17 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0187_auto_20200317_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default=None, max_length=255)),
                ('type', models.CharField(default=None, max_length=255)),
                ('z_createdTimeStamp', models.DateTimeField(default=None)),
                ('z_expiryTimeStamp', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.DeleteModel(
            name='Zoho_tokens',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='api_booking_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='api.API_booking_quotes'),
        ),
    ]
