# Generated by Django 2.1.2 on 2020-03-17 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0189_auto_20200317_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='api_booking_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='z_createdTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 19, 31, 2, 771190)),
        ),
    ]
