# Generated by Django 2.1.2 on 2020-05-14 00:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0199_auto_20200509_0337"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailerProducts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "item_number",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "item_description",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                ("dim_uom", models.CharField(max_length=32)),
                ("length", models.FloatField(blank=True, default=None, null=True)),
                ("width", models.FloatField(blank=True, default=None, null=True)),
                ("height", models.FloatField(blank=True, default=None, null=True)),
                ("weight_uom", models.CharField(max_length=32)),
                ("weight", models.FloatField(blank=True, default=None, null=True)),
                (
                    "warehouse",
                    models.ManyToManyField(
                        related_name="retailer_products", to="api.Client_warehouses"
                    ),
                ),
            ],
        ),
    ]
