# Generated by Django 2.1.2 on 2020-05-14 00:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0200_auto_20200514_0008"),
    ]

    operations = [
        migrations.AlterModelTable(name="retailerproducts", table="retailer_products",),
    ]
