# Generated by Django 2.1.2 on 2020-06-02 22:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0201_auto_20200520_0400"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client_Products",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "modelNumber",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Model Number",
                    ),
                ),
                (
                    "e_dimUOM",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Dim UOM"
                    ),
                ),
                (
                    "e_weightUOM",
                    models.CharField(
                        blank=True, max_length=56, null=True, verbose_name="Weight UOM"
                    ),
                ),
                (
                    "e_dimLength",
                    models.FloatField(blank=True, null=True, verbose_name="Dim Length"),
                ),
                (
                    "e_dimWidth",
                    models.FloatField(blank=True, null=True, verbose_name="Dim Width"),
                ),
                (
                    "e_dimHeight",
                    models.FloatField(blank=True, null=True, verbose_name="Dim Height"),
                ),
                (
                    "e_weightPerEach",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Weight Per Each"
                    ),
                ),
                (
                    "fk_id_dme_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.DME_clients",
                    ),
                ),
            ],
            options={"db_table": "client_products",},
        ),
        migrations.AddField(
            model_name="dme_options",
            name="show_in_admin",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
