# Generated by Django 2.1.2 on 2020-05-14 01:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0202_auto_20200514_0022"),
    ]

    operations = [
        migrations.RemoveField(model_name="client_employees", name="warehouses",),
        # migrations.AddField(
        #     model_name='bookings',
        #     name='z_connote_url',
        #     field=models.CharField(blank=True, default='', max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='bookings',
        #     name='z_downloaded_connote_timestamp',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        migrations.AddField(
            model_name="client_employees",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Client_warehouses",
            ),
        ),
        # migrations.AlterField(
        #     model_name='bok_2_lines',
        #     name='pk_booking_lines_id',
        #     field=models.CharField(blank=True, max_length=64, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='bok_3_lines_data',
        #     name='fk_booking_lines_id',
        #     field=models.CharField(blank=True, default=None, max_length=64),
        # ),
        # migrations.AlterField(
        #     model_name='booking_lines_data',
        #     name='fk_booking_lines_id',
        #     field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='FK Booking Lines Id'),
        # ),
        # migrations.AlterField(
        #     model_name='bookings',
        #     name='api_booking_quote',
        #     field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.API_booking_quotes'),
        # ),
        # migrations.AlterField(
        #     model_name='tokens',
        #     name='z_createdTimeStamp',
        #     field=models.DateTimeField(default=datetime.datetime.now),
        # ),
    ]
