# Generated by Django 2.1.2 on 2020-06-03 23:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0202_auto_20200603_0838"),
    ]

    operations = [
        migrations.AddField(
            model_name="dme_clients",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.DME_clients",
            ),
        ),
    ]
