# Generated by Django 2.1.2 on 2020-05-14 02:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0203_auto_20200514_0118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailerproducts",
            name="item_description",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tokens",
            name="z_createdTimeStamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
