# Generated by Django 2.1.2 on 2020-06-03 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0203_auto_20200604_0949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dme_clients",
            name="phone",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
