# Generated by Django 2.1.2 on 2020-06-08 02:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0204_auto_20200604_0959"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookings", name="b_client_name_sub",),
        migrations.AddField(
            model_name="bookings",
            name="sub_client_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.DME_clients",
            ),
        ),
    ]
