# Generated by Django 2.1.2 on 2020-06-08 03:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0205_auto_20200608_0259"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookings", old_name="sub_client_id", new_name="sub_client",
        ),
    ]
