# Generated by Django 2.1.2 on 2021-08-30 00:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0278_auto_20210822_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='DME_SMS_Templates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('smsName', models.CharField(blank=True, max_length=255, null=True)),
                ('smsMessage', models.TextField(blank=True, null=True)),
                ('z_createdByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by account')),
                ('z_createdTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by account')),
                ('z_modifiedTimeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'dme_sms_templates',
            },
        ),
        migrations.RemoveField(
            model_name='log',
            name='z_createdBy',
        ),
        migrations.RemoveField(
            model_name='log',
            name='z_modifiedBy',
        ),
        migrations.AddField(
            model_name='dme_clients',
            name='logo_url',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Logo Url'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='api_booking_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='client_overrided_quote',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fc_log',
            name='new_quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='fc_log',
            name='old_quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.API_booking_quotes'),
        ),
    ]
