# Generated by Django 2.1.2 on 2022-01-17 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0296_auto_20220110_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dme_clients',
            name='logo_url',
        ),
    ]
