# Generated by Django 2.1.2 on 2022-01-17 03:23

from django.db import migrations


class Migration(migrations.Migration):

    operations = [
        migrations.RemoveField(
            model_name='dme_clients',
            name='logo_url',
        ),
    ]
