# Generated by Django 2.1.2 on 2022-01-24 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    operations = [
        migrations.CreateModel(
            name='FPContacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=20)),
                ('last_name', models.CharField(default=None, max_length=20)),
                ('company', models.CharField(default=None, max_length=20)),
                ('department', models.CharField(default=None, max_length=20, null=True)),
                ('email_address', models.CharField(default=None, max_length=40, null=True)),
                ('job_title', models.CharField(default=None, max_length=64, null=True)),
                ('company_main_phone', models.CharField(default=None, max_length=64, null=True)),
                ('home_phone', models.CharField(default=None, max_length=64, null=True)),
                ('mobile_phone', models.CharField(default=None, max_length=64, null=True)),
                ('notes', models.CharField(default=None, max_length=100, null=True)),
                ('webpage', models.CharField(default=None, max_length=160, null=True)),
                ('business_street1', models.CharField(default=None, max_length=64, null=True)),
                ('business_street2', models.CharField(default=None, max_length=64, null=True)),
                ('business_city', models.CharField(default=None, max_length=64, null=True)),
                ('business_country', models.CharField(default=None, max_length=64, null=True)),
                ('business_fax', models.CharField(default=None, max_length=64, null=True)),
                ('business_phone', models.CharField(default=None, max_length=64, null=True)),
                ('business_phone2', models.CharField(default=None, max_length=64, null=True)),
                ('business_state', models.CharField(default=None, max_length=64, null=True)),
                ('business_postal_code', models.IntegerField(verbose_name='postal code')),
            ],
            options={
                'db_table': 'fp_contacts',
            },
        ),
    ]
