# Generated by Django 2.1.2 on 2022-03-03 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0306_auto_20220225_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp_freight_providers',
            name='hex_color_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
