# Generated by Django 2.1.2 on 2022-07-26 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0323_auto_20220714_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='dme_client_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
