# Generated by Django 2.1.2 on 2022-09-06 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0329_auto_20220826_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name="fp_freight_providers",
            name="last_atl_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookings",
            name="fp_atl_number",
            field=models.IntegerField(default=0),
        ),
    ]
