# Generated by Django 2.1.2 on 2023-01-09 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0339_auto_20221228_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreBookingError',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pk_booking_id', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Booking ID')),
                ('api_type', models.CharField(default=None, max_length=64, null=True)),
                ('error', models.CharField(default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Timestamp')),
                ('resolved_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Resolved Timestamp')),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(default='open', max_length=15, null=True)),
                ('resolved_by', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dme_prebooking_errors',
            },
        ),
    ]
