# Generated by Django 2.1.2 on 2018-11-19 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_employees',
            fields=[
                ('pk_id_client_emp', models.AutoField(primary_key=True, serialize=False)),
                ('name_last', models.CharField(max_length=30, verbose_name='last name')),
                ('name_first', models.CharField(max_length=30, verbose_name='first name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.IntegerField(verbose_name='phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Warehouse',
            fields=[
                ('pk_id_client_warehouse', models.AutoField(primary_key=True, serialize=False)),
                ('warehoursename', models.CharField(max_length=230, verbose_name='warehoursename')),
                ('warehouse_address1', models.TextField(verbose_name='warehouse address1')),
                ('warehouse_address2', models.TextField(verbose_name='warehouse address2')),
                ('warehouse_state', models.TextField(verbose_name='warehouse state')),
                ('warehouse_suburb', models.TextField(verbose_name='warehouse suburb')),
                ('warehouse_phone_main', models.IntegerField(verbose_name='warehouse phone number')),
                ('warehouse_hours', models.IntegerField(verbose_name='warehouse hours')),
            ],
        ),
        migrations.CreateModel(
            name='DME_clients',
            fields=[
                ('pk_id_dme_client', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=230, verbose_name='warehoursename')),
                ('dme_account_num', models.IntegerField(verbose_name='dme account num')),
                ('phone', models.IntegerField(verbose_name='phone number')),
            ],
        ),
        migrations.CreateModel(
            name='DME_employees',
            fields=[
                ('pk_id_dme_emp', models.AutoField(primary_key=True, serialize=False)),
                ('name_last', models.CharField(max_length=30, verbose_name='last name')),
                ('name_first', models.CharField(max_length=30, verbose_name='first name')),
                ('Role', models.TextField(verbose_name='Role')),
                ('fk_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client_warehouse',
            name='fk_id_dme_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.DME_clients'),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='fk_id_client_warehouse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.Client_Warehouse'),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='fk_id_dme_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.DME_clients'),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='fk_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
