# Generated by Django 2.1.2 on 2018-11-19 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=230, verbose_name='booking id')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('booked_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='booked date')),
                ('pickup_from_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='pickup from date')),
                ('ref_number', models.IntegerField(verbose_name='ref number')),
                ('status', models.CharField(max_length=230, verbose_name='status')),
                ('freight_provider', models.CharField(max_length=30, verbose_name='freight provider')),
                ('service', models.CharField(max_length=230, verbose_name='service')),
                ('pickup_by', models.CharField(max_length=230, verbose_name='pickup by')),
                ('latest_delivery', models.CharField(max_length=230, verbose_name='latest devlivery')),
                ('consignment', models.CharField(max_length=230, verbose_name='consignment')),
                ('pick_up_entity', models.CharField(max_length=230, verbose_name='booking id')),
                ('delivery_entity', models.CharField(max_length=230, verbose_name='booking id')),
            ],
        ),
    ]
