# Generated by Django 2.1.2 on 2018-12-14 12:36

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='label_base64',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=255, null=True, verbose_name='Based64 Label'),
        ),
    ]
