# Generated by Django 2.1.2 on 2018-12-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='label_base64',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Based64 Label'),
        ),
    ]
