# Generated by Django 2.1.2 on 2018-12-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_bookings_label_base64'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='label_base64',
            new_name='shipping_label_base64',
        ),
    ]
