# Generated by Django 2.1.2 on 2018-12-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20181214_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='b_client_name',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='Client Name'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='fk_fp_pickup_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='KF FP pickup id'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kf_client_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='KF Client ID'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pk_booking_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Booking ID'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pu_pickup_instructions_address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pickup instrunctions address'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='zb_002_client_booking_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Client Booking Key'),
        ),
    ]
