# Generated by Django 2.1.2 on 2018-12-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20181214_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='b_bookingID_Visual',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='BookingID Visual'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='b_clientReference_RA_Numbers',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Client Reference Ra Numbers'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='b_client_name',
            field=models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='b_status',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='consignment_label_link',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Consignment'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='deToCompanyName',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='error_details',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Error Detail'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='fk_fp_pickup_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='KF FP pickup id'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='kf_client_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='KF Client ID'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pk_booking_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Booking ID'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='puCompany',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_pickup_instructions_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Pickup instrunctions address'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='v_FPBookingNumber',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='FP Booking Number'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='vx_freight_provider',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Freight Provider'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='vx_serviceName',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='zb_002_client_booking_key',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Client Booking Key'),
        ),
    ]
