# Generated by Django 2.1.2 on 2018-12-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20181214_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='b_status',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Status'),
        ),
    ]
