# Generated by Django 2.1.2 on 2018-12-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20181214_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='bok_1_headers',
            name='success',
            field=models.CharField(default=0, max_length=1, verbose_name='Success'),
        ),
        migrations.AddField(
            model_name='bok_2_lines',
            name='success',
            field=models.CharField(default=0, max_length=1, verbose_name='Success'),
        ),
    ]
