# Generated by Django 2.1.2 on 2018-12-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20181215_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bok_2_lines',
            name='client_booking_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Client booking id'),
        ),
        migrations.AlterField(
            model_name='bok_2_lines',
            name='l_002_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Address Postal Code'),
        ),
        migrations.AlterField(
            model_name='bok_2_lines',
            name='l_003_item',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='bok_2_lines',
            name='l_009_weight_per_each',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight per each'),
        ),
        migrations.AlterField(
            model_name='bok_2_lines',
            name='l_010_totaldim',
            field=models.FloatField(blank=True, null=True, verbose_name='Totaldim'),
        ),
        migrations.AlterField(
            model_name='bok_2_lines',
            name='l_500_client_run_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Client run code'),
        ),
        migrations.AlterField(
            model_name='bok_2_lines',
            name='l_501_client_UOM',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Client UOM'),
        ),
        migrations.AlterField(
            model_name='bok_2_lines',
            name='l_cubic_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Cubic Weight'),
        ),
        migrations.AlterField(
            model_name='bok_2_lines',
            name='success',
            field=models.CharField(blank=True, default=0, max_length=1, null=True, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='bok_2_lines',
            name='v_client_pk_consigment_num',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Consigment num'),
        ),
    ]
