SURCHARGE_NAME_DESC = {
    "ALLIED": {
        "Lengths [LSC] 1.20-2.39 metre": "Items that exceed lenghts in any direction will attract a surcharge",
        "Lengths [LSC] 2.40-3.59 metre": "Items that exceed lenghts in any direction will attract a surcharge",
        "Lengths [LSC] 3.60-4.19 metre": "Items that exceed lenghts in any direction will attract a surcharge",
        "Lengths [LSC] 4.20-4.79 metre": "Items that exceed lenghts in any direction will attract a surcharge",
        "Lengths [LSC] 4.80-5.99 metre": "Items that exceed lenghts in any direction will attract a surcharge",
        "Lengths [LSC] over 6 metre": "Items that exceed lenghts in any direction will attract a surcharge",
        "Width [WS] 1.10-1.60 metre": "Items that exceed widthwill attract a surcharge",
        "Width [WS] 1.61-2.4 metre": "Items that exceed widthwill attract a surcharge",
        "Tail Lift [TL]": "For deliveries requiring tail lifts",
        "Oversize Pallets": "Standard pallet sizes are measured at a maximum of 1.2m x 1.2m x 1.4m and weighed at a maximum of 500 kilograms. Pallets greater than will incur oversize pallet charges, in line with the number of pallet spaces occupied, charged in full pallets. An additional pallet charge will apply.",
        "Minimum Charge-Skids/ Pallets": "The minimum charge for a skid is 175 kilograms, and for a pallet is 350 kilograms.  Please note that even if your freight is not presented on a pallet or skid, these charges may be applied if items cannot be lifted by one person.",
        "HD": "FREIGHT OVERSIZED HOME DELIVERY",
        "LSC": "LENGTH SURCHARGE",
        "MHF": "MANUAL HANDLING FEE",
        "Onforwarding(Pickup)": "All our rates apply from pick up and to drop, where a delivery made to a nominated regional, country or remote location, as outlined on our Onforwarding matrix, an onforwarding surcharge is applicable.  Please contact Allied Express for a copy of this matrix.",
        "Onforwarding(Delivery)": "All our rates apply from pick up and to drop, where a delivery made to a nominated regional, country or remote location, as outlined on our Onforwarding matrix, an onforwarding surcharge is applicable.  Please contact Allied Express for a copy of this matrix.",
        "Overweight": "Base charge plus kilo charge",
        "Home Deliveries [HD]": "The Home delivery fee’s would be 50% less than what is shown, so we know it is not the standard price. For freight being delivered to residential addresses a surcharge per consignment between 23 and 55 kgs (dead or cubic weight)",
    },
    "HUNTER": {
        "Excess Lengths (2.5m+)": "2.5m up to/not incl. 4.0m",
        "Excess Lengths (4.0m+)": "4.0m up to/not incl. 6.0m",
        "Excess Lengths (6.0m+)": "6.0m and greater",
        "Bulk Delivery to Residential Address - Average dead or cubic weight per item 34-49kg": "",
        "Bulk Delivery to Residential Address - Average dead or cubic weight per item 50-74kg": "",
        "Bulk Delivery to Residential Address - Average dead or cubic weight per item 75-99kg": "",
        "Bulk Delivery to Residential Address - Average dead or cubic weight per item 100kg or greater": "",
        "Tail-Lift Truck8(pickup)": "",
        "Tail-Lift Truck8(delivery)": "",
    },
    "TNT": {
        "Dangerous Goods (Road Express)": "Surcharge per consignment. In addition, the MHP Fee will apply per item to each and all items consigned under the same consignment note where that consignment contains Dangerous Goods, including any non-Dangerous Goods items consigned under that consignment note. (Dangerous Goods consignment notes are to contain Dangerous Goods items only.)",
        "Dangerous Goods (excluding Road Express)": "Surcharge per consignment. In addition, the MHP Fee will apply per item to each and all items consigned under the same consignment note where that consignment contains Dangerous Goods, including any non-Dangerous Goods items consigned under that consignment note. (Dangerous Goods consignment notes are to contain Dangerous Goods items only.)",
        "Residential Pickup (RSP)": "Fee per consignment for pick up from a residential address4.",
        "Heavyweight Residential Pickup (RSP30)": "Fee per consignment for pick up from a residential address4 with a chargeable weight5 of 30kg and over, but less than 100kg.6 This fee will be applied in addition to any other fee or surcharge in relation to the consignment, including the existing Residential Delivery Fee (RSD) and/or Residential Pickup Fee (RSP) of $5 per consignment for delivery to and/or pickup from a residential address4.",
        "Heavyweight Residential Pickup (RSP100)": "Fee per consignment for pick up from a residential address4 with a chargeable weight5 of 100kg and over.6 This fee will be applied in addition to any other fee or surcharge in relation to the consignment, including the existing Residential Delivery Fee (RSD) and/or Residential Pickup Fee (RSP) of $5 per consignment for delivery to and/or pickup from a residential address4.",
        "Residential Delivery (RSD)": "Fee per consignment for delivery to a residential address4.",
        "Heavyweight Residential Delivery (RSD30)": "Fee per consignment for delivery from a residential address4 with a chargeable weight5 of 30kg and over, but less than 100kg. 6 This fee will be applied in addition to any other fee or surcharge in relation to the consignment, including the existing Residential Delivery Fee (RSD) and/or Residential Pickup Fee (RSP) of $5 per consignment for delivery to and/or pickup from a residential address4.",
        "Heavyweight Residential Delivery (RSD100)": "Fee per consignment for delivery from a residential address4 with a chargeable weight5 of 100kg and over.6 This fee will be applied in addition to any other fee or surcharge in relation to the consignment, including the existing Residential Delivery Fee (RSD) and/or Residential Pickup Fee (RSP) of $5 per consignment for delivery to and/or pickup from a residential address4. 4 ’Residential address’ means a home or private residence, including locations where a business is operated from the home or private residence, and/or a shipment in which the shipper has designated the delivery/pickup address as residential. 5 This fee will be applied to each consignment’s chargeable weight, which is the greater of the dead weight and the cubic weight, calculated in accordance with the TNT Australia Pty Limited Terms and Conditions of Carriage and other services. 6 Weight limitations will be subject to TNT’s health and safety guidelines and/or operation constraints.",
        "Oversize Freight (OS0)": "Oversize freight where any one dimension (length, height or width) exceeds 1.49 metres.",
        "Oversize Freight (OS1)": "Oversize freight where any one dimension (length, height or width) exceeds 1.99 metres.",
        "Oversize Freight (OS2)": "Oversize freight where any one dimension (length, height or width) exceeds 2.99 metres.",
        "Oversize Freight (OS3)": "Oversize freight where any one dimension (length, height or width) exceeds 3.99 metres.",
        "Oversize Freight (OS4)": "Oversize freight where any one dimension (length, height or width) exceeds 4.99 metres.",
        "Oversize Freight (OS5)": "Oversize freight where any one dimension (length, height or width) exceeds 5.99 metres.",
    },
}
